# Generated by Django 6.0.2 on 2026-02-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.TextField(max_length=50)),
                ('EventName', models.TextField(max_length=50)),
                ('Location', models.TextField(max_length=50)),
                ('Date', models.DateField(max_length=50)),
                ('Description', models.TextField()),
                ('Image', models.ImageField(upload_to='events/')),
            ],
        ),
    ]
