# Generated by Django 6.0.2 on 2026-03-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_eventdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydb',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='eventdb',
            name='Date',
        ),
        migrations.AddField(
            model_name='categorydb',
            name='Category_Image',
            field=models.ImageField(default='default.jpg', upload_to='Category/'),
            preserve_default=False,
        ),
    ]
