# Generated by Django 6.0.2 on 2026-03-08 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0003_remove_categorydb_image_remove_eventdb_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdb',
            name='Price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorydb',
            name='Description',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='eventdb',
            name='Description',
            field=models.TextField(max_length=50),
        ),
    ]
