# Generated by Django 6.0.2 on 2026-03-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Subject', models.TextField(max_length=50)),
                ('Message', models.TextField(max_length=50)),
            ],
        ),
    ]
