# Generated by Django 6.0.2 on 2026-03-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizerapp', '0002_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Date', models.DateField()),
                ('Category_Name', models.TextField(max_length=50)),
                ('EventName', models.TextField(max_length=50)),
                ('Location', models.TextField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Price', models.TextField(max_length=50)),
                ('Address', models.TextField(max_length=50)),
                ('Message', models.TextField(max_length=50)),
                ('status', models.TextField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
            ],
        ),
    ]
