# Generated by Django 6.0.2 on 2026-03-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizerapp', '0003_bookingdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='Date',
            field=models.DateField(unique=True),
        ),
    ]
