# Generated by Django 6.0.2 on 2026-03-21 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizerapp', '0004_alter_bookingdb_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=10)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizerapp.registration')),
            ],
        ),
    ]
