# Generated by Django 6.0.2 on 2026-03-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizerapp', '0005_reviewdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewdb',
            name='user',
        ),
        migrations.AddField(
            model_name='reviewdb',
            name='Name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
