# Generated by Django 6.0.2 on 2026-03-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizerapp', '0007_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='payment_status',
            field=models.TextField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid'),
        ),
    ]
