# Generated by Django 6.0.2 on 2026-03-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizerapp', '0008_bookingdb_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdb',
            name='Price',
            field=models.IntegerField(),
        ),
    ]
